version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: onboarding
      POSTGRES_PASSWORD: onboarding
      POSTGRES_DB: onboarding
    volumes:
       - ./data:/var/lib/postgresql/data